services:
  postgres:
    image: postgres:17
    ports:
      - 5400:5432
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: my_db
    volumes:
      - my-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
    volumes:
      - my-pgadmin:/var/lib/pgadmin

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      #
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: my_db
    command: >
      sh -c "uv run alembic upgrade head && uv run uvicorn src.main:app --host 0.0.0.0 --port 8000"

volumes:
  my-pgdata:
  my-pgadmin:
